#####################################################################
# This file contains the graphic configuration. it will be 
# regenerated by the game. so dont add new commands here.
#####################################################################

let r_gldriver	libGL.so
let r_gldriver_win32	opengl32.dll
let r_devicewidth	640
let r_deviceheight	480
let r_devicerefresh	85
let r_viewwidth	600
let r_viewheight	480
let r_gamma	1.0
